version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "c2a-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bb5ndid0a5rc"
s3_prefix = "c2a-test"
region = "us-east-1"
profile = "ChristyC2ATestDeploy"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "ProjectName=\"commit2act\" EnvironmentName=\"dev\" DBName=\"sys\" DBUser=\"admin\" DBPassword=\"testpass\" DBInstanceClass=\"db.t4g.large\" DBEngineVersion=\"5.7.mysql_aurora.2.09.2\" DeletionProtection=\"False\" EncryptDatabase=\"True\" CloudFrontPriceClass=\"PriceClass_100\" MinConfidenceThreshold=\"70\" CognitoAdminName=\"christy\" CognitoAdminEmail=\"christy.lam@ubc.ca\""
image_repositories = []
